# Change these first
owner: TransitTracker # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Transit Tracker
    url: https://www.transittracker.ca
  - name: Transit Tracker API
    url: https://api.transittracker.ca/v2/regions
  - name: Transit Tracker VIN
    url: https://vin.transittracker.ca

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/TransitTracker/frontend/refs/heads/main/static/img/logo.svg
  themeUrl: https://raw.githubusercontent.com/TransitTracker/upptime/refs/heads/master/assets/theme.css
  name: Transit Tracker status
  navbar:
    - title: Status
      href: /
    - title: Back to the app
      href: https://www.transittracker.ca

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
